"""MOE Ethiopia Internal Inspection Checklist 2017 Primary/Middle NG schools."""


def crit(am, en):
    return {"titleAm": am, "titleEn": en}


def ind(code, mp, tam, ten, sources, *criteria):
    std = int(code.split(".")[0])
    return {
        "code": code,
        "standardNumber": std,
        "maxPoints": mp,
        "titleAm": tam,
        "titleEn": ten,
        "dataSources": list(sources),
        "criteria": [crit(am, en) for am, en in criteria],
    }


ALL_INDICATOR_SPECS = [
    ind(
        "1.1", 1,
        'ትምህርት ቤቱ ተፈላጊውን የቦታ ስፊትና የይዞታ ሰነድ ምልከታ እና ቃል ማረጋገጫ ስላሟላ',
        'The school has completed verification of appropriate land area and ownership documents',
        ("DOCUMENT_REVIEW", "OBSERVATION", "INTERVIEW"),
        crit('ትምህርት ቤቱ ተፈላጊ የቦታ ስፊትና የይዞታ ሰነዶች በምልከታ እና በሰነድ ማረጋገጥ ተሟልቷል', 'Appropriate land area and ownership documents have been verified through observation and document review'),
        crit('የትምህርት ቤቱ ምድር ግቢ ለአንደኛና መካከለኛ ደረጃ ትምህርት ቤት የቦታ ስፊት ቢያንስ 15,566 ካሬ ሜትር ሊኖረው ይገባል', 'The school compound land area is at least 15,566 square metres for primary and middle level'),
        crit('ቅጥር ግቢው እንደ አካባቢው ተጨባጭ ሁኔታ በድንጋይ፣ በብልጽግግ፣ በእሾህ አረንጓዴ ሽቦና በእንጨት አጥር ሙሉ በሙሉ የታጠረ', 'The compound is fully fenced with stone, brick, eucalyptus mortar, or wooden fence as appropriate to the locality'),
        crit('በትምህርት ቤቱ የይዞታ ማረጋገጫ ህጋዊ ሰነድ መኖሩ', 'The school possesses legal documentation confirming land ownership'),
    ),
    ind(
        "1.2", 1,
        'ትምህርት ቤቱና የአካባቢው ማህበረሰብ የሚገለግለበት መሰረተ ልማቶች በስታንዲርድ መሰረት የተነቁ',
        'Community-shared infrastructure facilities are built per standard',
        ("DOCUMENT_REVIEW", "OBSERVATION", "INTERVIEW"),
        crit('የቤተ-መጽሃፍት 7×24=168 ካ.ሜ፣ ከመጻሕፍት ግምጃ ቤት ጋር ብርሃንና ሰፉ የማንበቢያ ቦታ', 'Library 168 sq m (7×24) with bookstore, adequate lighting and reading space'),
        crit('ሁሉንም ገብ አዳራሽ 7×24=168 ካ.ሜ (መሰብሰቢያ፣ መመገቢያና ልዩ ልዩ ሁኔታዎችን ማከናወን)', 'Assembly hall 168 sq m (7×24) serving collection, entry and separate functions'),
        crit('የመጀመሪያ ደረጃ እርዳታ መስጫ ክፍል 7×8=56 ካ.ሜ', 'First aid room 56 sq m (7×8)'),
        crit('የፅዳት ሰራተኞች መሸጎጫና የፅዳት እቃዎች ማስቀመጫ ክፍል 3×3=9 ካ.ሜ', 'Janitor room and cleaning supplies storage 9 sq m (3×3)'),
        crit('መኖሪያ ቤት ለር/መም/ር 7×10=70 እና 7×10=70 በገጠር 140 ካ.ሜ፤ ለመምህራን 5×6=30 በደግሙ 300 ካ.ሜ', "Principal residence 70+70 sq m in rural (140 total); teachers' quarters 30 sq m each, 300 sq m total in urban"),
        crit('የእግር ኳስ ሜዳ 45×90=4,050 ካ.ሜ', 'Football pitch 4,050 sq m (45×90)'),
        crit('የመረብ ኳስ ሜዳ 20×16=320 ካ.ሜ', 'Volleyball court 320 sq m (20×16)'),
        crit('የቅርጫት ኳስ 20×16=220 ካ.ሜ', 'Basketball court 220 sq m (20×16)'),
        crit('የእጅ ኳስ ሜዳ 20×11=220 ካ.ሜ', 'Handball court 220 sq m (20×11)'),
        crit('የከፍታ ዝላይ 20×15=300 ካ.ሜ', 'High jump area 300 sq m (20×15)'),
        crit('የትምህርት ቤቱን ስፋት መሰረት በማድረግ ሁሉንም ገብ ስፖርት መሰረተ ልማት ተዘጋጅቷል', 'Full-size athletics track and field prepared based on school site dimensions'),
        crit('ቤተ-መጽሃፍት፣ አዳራሽና የስፖርት ቦታዎች በስታንዲርድ መሰረት የተነቁ', 'Library, hall and sports facilities built per standard'),
    ),
    ind(
        "1.3", 1,
        'የመማር ማስተማር ተግባር የሚካሄድባቸው መሰረተ ልማቶች በስታንዲርድ መሰረት የተነቁ',
        'Teaching-learning infrastructure facilities are built per standard',
        ("DOCUMENT_REVIEW", "OBSERVATION"),
        crit('መማሪያ ክፍሎች ለ40 ተማሪዎች የሚበቁ 7×8=56 ካ.ሜ', 'Classrooms 56 sq m (7×8) accommodating 40 students'),
        crit('የመምህራን እና አስተዳደር ሰራተኞች ማረፊያ 7×8=56 ካ.ሜ', "Teachers' and admin staff room 56 sq m"),
        crit('አስተዳደር ቢሮዎች ከሲሚንቶ፣ ከአሸዋ፣ ከከሰት መሰራት', 'Admin offices built with cement, sand and gravel'),
        crit('የር/መም/ር ቢሮ 4×5=20 ካ.ሜ', "Principal's office 20 sq m (4×5)"),
        crit('የም/ር/መም/ር ቢሮ እንደ ብዛታቸው 4×5=20 ካ.ሜ', 'Deputy principal office(s) 20 sq m each (4×5)'),
        crit('የጸሀፊና እንግዳ መቀበያ ቢሮ 4×4=16 ካ.ሜ', 'Secretary and reception office 16 sq m (4×4)'),
        crit('የመምህራን እረፍት ቤት 3×6=18 ካ.ሜ', "Teachers' lounge 18 sq m (3×6)"),
        crit('የትምህርት መርጃ መሳርያዎች ማከማቻና ስርጭት 4×8=32 ካ.ሜ', 'Educational materials storage and distribution 32 sq m (4×8)'),
        crit('የመርጃ መሳሪያዎች ማምረቻ ክፍል 4×8=32 ካ.ሜ', 'Materials production room 32 sq m (4×8)'),
        crit('ሪከርድና ማህደር ክፍል 4×5=20 ካ.ሜ', 'Records and archive room 20 sq m (4×5)'),
        crit('ለክበባት የሚሆን ክፍል 4×8=32 ካ.ሜ', 'Counselling room 32 sq m (4×8)'),
        crit('ለመምህራንና አስተዳደር ሰራተኞች የህፃናት ማቆያ (Day care) 4×8=32 ካ.ሜ', 'Day care for teachers and admin staff 32 sq m (4×8)'),
        crit('የልዩ ትምህርት ክፍል 7×8=56 ካ.ሜ', 'Special needs education classroom 56 sq m (7×8)'),
        crit('የሳይንስ ክፍል 7×8=56 ካ.ሜ (ከ1-6ኛ ክፍሎች ብቻ)', 'Science room 56 sq m for grades 1–6 only'),
        crit('ሁሉንም ገብ የሳይንስና የሂሳብ ማዕከል/ቤተ-ሙከራ 7×16=112 ካ.ሜ (7-8ኛ)', 'Combined science and maths centre/lab 112 sq m (7×16) for grades 7–8'),
        crit('የኢንፎርሜሽን ቴክኖሎጂ ማዕከል 7×8=56 ካ.ሜ', 'IT centre 56 sq m (7×8)'),
        crit('የቋንቋ ማዕከል 7×8=56 ካ.ሜ', 'Language centre 56 sq m (7×8)'),
        crit('እቃ ግምጃቤት 4×10=40 ካ.ሜ', 'Inventory/store room 40 sq m (4×10)'),
    ),
    ind(
        "1.4", 0.5,
        'በቂ፣ ደረጃቸውን የጠበቁ፣ በየጊዜው የሚፀድና በፆታ የተለዩ የተማሪ፣ መምህርና ሰራተኞች መፀዳጃ ቤቶች ከውሃ ጋር',
        'Adequate, standard-compliant, maintained and gender-separated toilets with water supply exist',
        ("OBSERVATION", "INTERVIEW"),
        crit('የተማሪ መፀዳጃ ክፍል በፆታ የተለዩ፣ 30 ሜትር ርቀት፣ 4×5=20 ካ.ሜ (ገጠር: ወ 1:75/ሴ 1:50፤ ከተማ: ወ 1:50/ሴ 1:25)', 'Student toilets gender-separated, 30 m apart, 20 sq m cubicles; ratios per rural/urban standard'),
        crit('መፀዳጃ ለመምህራንና ለሠራተኞች በፆታ የተለዩ 4×5=20 ካ.ሜ', 'Teacher and staff toilets gender-separated, 20 sq m (4×5)'),
        crit('መፀዳጃ ቤቶች ደረጃቸውን የጠበቁ፣ በየጊዜው የሚፀድኑ እና ከውሃ ጋር', 'Toilets meet standard, are regularly cleaned and have water supply'),
    ),
    ind(
        "1.5", 0.5,
        'ትምህርት ቤቱ በቂ ለመጠጥ የሚያገለግል የውሃ አቅርቦት',
        'The school has adequate drinking water supply',
        ("OBSERVATION", "INTERVIEW"),
        crit('ገጠር: 100 ተማሪዎች አንዴ ቧንቧ፤ ከተማ: 50 ተማሪዎች አንዴ ቧንቧ', 'Rural: one tap per 100 students; urban: one tap per 50 students'),
    ),
    ind(
        "1.6", 1,
        'ትምህርት ቤቱ ለህብረተሰቡ ስራ ማሳያ የሚያገለግሉ መሰረተ ልማቶች የተነቁ',
        'Community demonstration infrastructure is built per standard',
        ("OBSERVATION", "INTERVIEW"),
        crit('ለ7ኛና 8ኛ የእንጨትና ብረታ ብረት ስራ ማሳያ ክፍል 7×8=56 ካ.ሜ', 'Wood and metal workshop 56 sq m for grades 7–8'),
        crit('የእድ ጥበብና የእጅ ስራዎች ክፍል 7×8=56 ካ.ሜ', 'Fine arts and handicrafts room 56 sq m'),
        crit('ገጠር ቢያንስ 120 ካ.ሜ፤ ከተማ 60 ካ.ሜ የጓሮ/አትክልት መትከያ', 'Garden plot: min 120 sq m rural, 60 sq m urban with plantation'),
        crit('ስራ ማሳያ ክፍሎች ምቹ፣ ብርሃን 300-500 lux፣ አየር ማስተላለፊያና ቆሻሻ ማስወገጃ', 'Workshops convenient with 300–500 lux lighting, ventilation and waste disposal'),
    ),
    ind(
        "2.1", 1,
        'ትምህርት ቤቱና የአካባቢው ማህበረሰብ የሚገለግለበት (ቤተ-መጽሃፍት፣ ሁሉንም ገብ አዳራሽ፣ የስፖርት ቦታዎች) ቁሳቁሶች በስታንዲርድ መሰረት ተሟሉ',
        'Materials for community-shared facilities meet the standard',
        ("OBSERVATION", "INTERVIEW"),
        crit('ቤተ-መጽሃፍት ቢያንስ 40 የተማሪ መቀመጫ ወንበር', 'Library has at least 40 student seats'),
        crit('ቤተ-መጽሃፍት ቢያንስ 7 ጠረጴዛዎች', 'Library has at least 7 desks'),
        crit('ቤተ-መጽሃፍት ቢያንስ 1 ኮምፒውተር', 'Library has at least 1 computer'),
        crit('ቤተ-መጽሃፍት የባibliography ወንበር', 'Library has a reference bench'),
        crit('ቤተ-መጽሃፍት የባibliography ጠረጴዛ', 'Library has a reference desk'),
        crit('መጽሐፍ መደርደሪያ ቢያንስ 5', 'At least 5 book shelves per student ratio'),
        crit('የተማሪ መማሪያ መጽሐፍት ከየትምህርት ዓይነት ቢያንስ 5', 'At least five textbooks per subject'),
        crit('ማጣቀሻ መጽሐፍ ቢያንስ ለ1 ተማሪ 5', 'At least five reference books per student'),
        crit('ሁሉንም ገብ አዳራሽ አስፈላጊ ወንበሮችና ጠረጴዛዎች', 'Assembly hall has adequate chairs and desks'),
        crit('የስፖርት ኳሶች በስታንዲርድ', 'Sport balls meet standard'),
        crit('የአትላቲክስ መሳሪያ ቁሳቁሶች', 'Athletics equipment complete'),
        crit('የጅምናስቲክ መሳሪያ ቁሳቁሶች', 'Gymnastics equipment complete'),
        crit('የሜዳ ቁሳቁሶች ተሟልተዋል', 'Track equipment complete'),
    ),
    ind(
        "2.2", 1,
        'ት/ቤቱ የመማሪያ፣ የቤተ-ሙከራዎች፣ የመምህራን ማረፊያ፣ መመገቢያ አዳራሽ እና አስተዳደር ክፍሎችን አስፈላጊ ቁሳቁሶችን አሟላ',
        'Teaching, lab, staff lounge, assembly and admin rooms have adequate materials',
        ("OBSERVATION", "INTERVIEW", "DOCUMENT_REVIEW"),
        crit('መማሪያ ክፍል በ1 ዳስክ 2 ተማሪዎች 20 አርምቸር 40', 'Classroom: 20 armchairs and 40 seats at 1 desk per 2 students'),
        crit('ለመምህሩ ጠረጴዛ', 'Teacher desk provided'),
        crit('ለመምህሩ ወንበር', 'Teacher chair provided'),
        crit('ጥቁር ወይም ነጭ ሰላዲ', 'Blackboard or whiteboard in both cycles'),
        crit('የተማሪ መጽሐፍት 1:1', 'Student textbooks 1:1 ratio'),
        crit('ለቤተ-ሙከራ የተማሪዎች ረጅም ወንበር 40', 'Lab long benches for 40 students'),
        crit('ለቤተ-ሙከራ Stool 40', 'Lab stools for 40 students'),
        crit('የመምህሩ ስራ ማሳያ ጠረጴዛ', 'Teacher demonstration desk'),
        crit('ቁምሳጥን ክሊፕ እና ከታች ብዛት', 'Test tube clips and stands'),
        crit('ሲንክ ያላቸው የሙከራ ጠረጴዛዎች (7-8)', 'Lab tables with sinks for grades 7-8'),
        crit('የመምህራን ማረፊያ ጠረጴዛ', "Teachers' lounge tables"),
        crit('የት/ቤት የውስጥ መዝናኛ: ቼዝ፣ ቴብል ቴ�nis', 'Recreation: chess, table tennis'),
        crit('መምህራን ላንች በመምህር ቁጥር', 'Teacher lockers per teacher count'),
        crit('ሁሉንም ገብ አዳራሽ በአስፈላጊ ቁሳቁሶች ተሟሊ', 'Assembly hall fully equipped'),
        crit('አስተዳደር ቢሮዎች ተሟልተዋል', 'Admin offices equipped per standard'),
        crit('ቤተ-መዘክር ተሟሊ', 'Archive room equipped'),
        crit('እቃ ግምጃቤት: መደገፊያ ወንበር፣ እንግዳ ወንበር፣ ጠረጴዛ፣ ፋይል ካቢኔት', 'Store room: bench, guest chair, desk, filing cabinet'),
        crit('የመጀመሪያ ህክምና ክፍል ቁሳቁሶች', 'First aid room materials per standard'),
    ),
    ind(
        "2.3", 1,
        'ትምህርት ቤቱ ለህብረተሰቡ ለስራ ማሳያ የሚያገለግሉ ቁሳቁሶችን አሟላ',
        'Community demonstration materials are complete',
        ("OBSERVATION", "INTERVIEW"),
        crit('የእርሻ መሳሪያ ግብዓት ተሟሊ', 'Agriculture inputs complete'),
        crit('የእርባታ መሳሪያ ግብዓት ተሟሊ', 'Horticulture inputs complete'),
        crit('የእድ ጥበብ ስራ ማሳያ ግብዓቶች', 'Fine arts workshop materials complete'),
        crit('የእንጨትና ብረታ ብረት ግብዓት ተሟሊ', 'Wood and metal workshop materials complete'),
    ),
    ind(
        "3.1", 1,
        'በት/ቤቱ የሚገኙ የውስጥ-ለውስጥ መንገዶች ለሁለም ተማሪዎች ምቹ ናቸው',
        'Internal pathways are convenient for all students',
        ("OBSERVATION"),
        crit('የመንገዶች አቀማመጥ ከቦታ ለመንቀሳቀስ አመቺ', 'Path layout allows easy movement'),
        crit('የውስጥ-ለውስጥ እና የመግቢያ/መውጫ መንገዶች ምቹ', 'Internal and entry/exit paths are convenient'),
    ),
    ind(
        "3.2", 1,
        'የትምህርት ቤቱ አካባቢ ከአደጋ ጉዳiyot ነፃ ነው',
        'The school environment is free from hazards',
        ("OBSERVATION", "INTERVIEW"),
        crit('ከዋና መንገድ እና ከፍተኛ ትራፊክ ፍሰት የራቀ', 'Away from main road and heavy traffic'),
        crit('ከወንዞች፣ ገደሎች፣ ገበያና ፋብሪካ የራቀ', 'Away from rivers, gullies, markets and factories'),
        crit('ከአደጋ ድምፅ፣ ጫጫታ፣ መጥፎ ጃሪና መጠጥ ቤት የራቀ', 'Away from noise, quarries, bad odour and bars'),
        crit('ከቪዲዮ ቤት፣ ጫት/ሺሻ ቤት የራቀ', 'Away from video halls and chat/shisha houses'),
        crit('ት/ቤቱ ከተማሪ መኖሪያ 2 ኪ.ሜ በማይበልጥ', 'Within 2 km of student residences'),
        crit('ት/ቤቱ ለልዩ ፍላጎት ተማሪዎች ምቹ መንገድ አለው', 'Convenient internal paths for special needs students'),
    ),
    ind(
        "4.1", 1,
        'ትምህርት ቤቱ ልዩ የመማር ፍላጎት ላላቸው ተማሪዎች ምቹ ሁኔታ ፈጥሯል',
        'Convenient conditions exist for learners with special needs',
        ("INTERVIEW", "OBSERVATION"),
        crit('በስታንዲርድ መሰረት የመስማት/ማየት/አካል ጉዳት ቁሳቁስ', 'Materials for sensory and physical disability per standard'),
        crit('ለአካል ጉዳተኞች ምቹ መፀዳጃ', 'Convenient toilets for students with physical disabilities'),
        crit('ልዩ ፍላጎት ክፍል በቁሳቁስ ተሟሊ', 'Special needs classroom equipped per standard'),
    ),
    ind(
        "4.2", 1,
        'ትምህርት ቤቱ ለሴት ተማሪዎች ምቹ ሁኔታ ፈጥሯል',
        'Convenient conditions exist for female students',
        ("INTERVIEW", "OBSERVATION"),
        crit('የሴቶች የንፅህና መጠበቂያ ክፍል በስታንዲርድ ተሟሊ', "Girls' hygiene room equipped per standard"),
    ),
    ind(
        "5.1", 1,
        'ትምህርት ቤቱ የእውቀት ሀብት የሚያሰባስብበት እቅድ አዘጋጅቷል',
        'The school has prepared a plan to mobilize financial resources',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ት/ቤቱ በስትራቴጂና አመታዊ እቅድ የእውቀት ሀብት ማሰባሰብ ታቅዷል', 'School plan includes resource mobilization'),
    ),
    ind(
        "5.2", 2,
        'በትምህርት ቤቱ ቅድሚያ ትኩረት የሚሹ ጉዳዮች በበጀት ተደገፈዋል',
        'Priority issues are supported in the budget',
        ("DOCUMENT_REVIEW"),
        crit('ትምህርት ቤቱ ቅድሚያ ትኩረት ጉዳዮችን አይቷል', 'Priority issues identified'),
        crit('ቅድሚያ ጉዳዮች በበጀት ተደገፈዋል', 'Priority issues supported in budget'),
    ),
    ind(
        "6.1", 1,
        'ትምህርት ቤቱ ለደረጃው የሚመጥን የትምህርት ዝግጅት ያላቸው መምህራን አሟላ',
        'Teachers with appropriate qualifications are in place',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('መምህራን ዱፕሊኬት አልያቸው', 'No duplicate teacher assignments'),
        crit('መምህራን የሙያ ማስክታፈርያ አላቸው', 'Teachers hold professional certification'),
        crit('ልዩ ፍላጎት መምህር በዱፕሊኬት', 'Special needs teacher not duplicated'),
        crit('አዋጋ የልዩ ፍላጎት መምህር በዱፕሊኬት ተመረቀ', 'Assistant special needs teacher qualified'),
        crit('የተማሪ-መምህር ጥምርታ 1:40', 'Student-teacher ratio is 1:40'),
        crit('መምህራን ቁጥር በስታንዲርድ', 'Teacher numbers meet standard'),
    ),
    ind(
        "6.2", 1,
        'ትምህርት ቤቱ ለደረጃው የሚመጥን የትምህርት ዝግጅት ያላቸው አመራሮች አሟላ',
        'School leaders with appropriate qualifications are in place',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ር/መምህር የመጀመሪያ ዲግሪ እና የአመራር ስልጠና', 'Principal has first degree and leadership training'),
        crit('ም/ር/መምህር የመጀመሪያ ዲግሪ እና የአመራር ስልጠና', 'Deputy has first degree and leadership training'),
        crit('ሱፐርቫይዘር የመጀመሪያ ዲግሪ እና የአመራር ስልጠና', 'Supervisor has first degree and leadership training'),
        crit('በትምህርት አመራር የሙያ ማስክታፈርያ', 'Leadership staff hold professional certification'),
        crit('አመራሮች ቁጥር በስታንዲርድ', 'Leadership numbers meet standard'),
    ),
    ind(
        "6.3", 1,
        'ትምህርት ቤቱ ለደረጃው የሚመጥን የአስተዳደር ሰራተኞችን አሟላ',
        'Administrative staff with appropriate qualifications are in place',
        ("DOCUMENT_REVIEW"),
        crit('ጥበቃ 8ኛ ክፍል ያጠናቀቀ', 'Security staff completed grade 8'),
        crit('የፅዳት ሰራተኛ 8ኛ ክፍል ያጠናቀቀ', 'Janitor completed grade 8'),
        crit('ንብረት/IT ባለሙያ IT ዲፕሎማ', 'Property/IT staff with IT diploma'),
        crit('አስተዳደር ሰራተኞች ቁጥር በስታንዲርድ', 'Admin staff numbers meet standard'),
    ),
    ind(
        "6.4", 1,
        'ትምህርት ቤቱ ተማሪዎችን በደረጃ መደበለ',
        'Students are assigned per grade standard',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ተማሪ ከ1-8 በክፍል እስከ 40', 'Grades 1-8 have up to 40 students per class'),
        crit('በልዩ ክፍል አንድ መምህር 10-20 ተማሪ', 'Special class: one teacher for 10-20 students'),
    ),
    ind(
        "7.1", 1,
        'አመራሩ የትምህርት ቤት ግምገማ አካሂዷል እና የሦስት ዓመት ስትራቴጂክ እና አመታዊ የመሻሻያ እቅድ አዘጋጅቷል',
        'Leader conducted self-assessment and prepared strategic and annual improvement plans',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የትምህርት ቤት መሻሻያ ኮሚቴ ተቋቋመ', 'School improvement committee established'),
        crit('የግምገማ መካሄድ የሚያሳዩ ሂደቶች ተደራጁ', 'Self-assessment process records organized'),
        crit('መምህራንና ባለሙያዎች በእቅድ ዝግጅት ተሳትፈዋል', 'Teachers and experts participated in plan preparation'),
        crit('እቅዱ ግብረ-መልስና ግምገማ ውጤቶችን ያካትታል', 'Plan incorporates feedback and assessment results'),
    ),
    ind(
        "8.1", 1,
        'ከትምህርት ቤት መሻሻያ ጋር ተያይዘው የሚመጡ የለውጥ ስራዎችን በአግባቡ አመራሩ ይመራል',
        'Leader appropriately manages innovation aligned with school improvement',
        ("INTERVIEW"),
        crit('ት/ቤቱ አዲስ አሰራሮችን በመቀበል የእቅድ አካላት አድርጓል', 'School adopted new practices as plan pillars'),
        crit('ት/ቤቱ የእቅድ አካላትን ተግባራዊ አድርጓል', 'School implemented plan pillars'),
    ),
    ind(
        "8.2", 1,
        'አመራሩ በትምህርት ቤቱ ዋና ተግባራትን በወቅቱ ይcommunicateዳል',
        'Leader communicates major school activities on time',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የትምህርትቤቱን ስትራቴጂና አመታዊ እቅድ በተያዘ ጊዜ ማስተዋወቅ', 'Strategy and annual plan communicated on schedule'),
        crit('የተማሪዎች ውጤትና ስነ-ምግባር ማስተዋወቅ', 'Student results and conduct communicated'),
        crit('የገቢና ወጪ ሒሳብ ማስተዋወቅ', 'Income and expenditure accounts communicated'),
    ),
    ind(
        "8.3", 1,
        'የትምህርት ቤቱ አመራር መልካም ልምዶችን ቀምሮ ተግባራዊ አድርጓል',
        'Leadership adopted and implemented good practices',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የተቀሰመ ልምድና እውቀት አለ', 'Adopted practice and knowledge documented'),
        crit('የተቀመረና ተግባራዊ የተደረገ ሰነድ አለ', 'Adopted practice documented and implemented'),
    ),
    ind(
        "8.4", 1,
        'አመራሩ እና ማህበረሰቡ ICT የተደገፈ የአሰራር ስርዓት ፈጥረዋል',
        'Leader and community created ICT-supported communication system',
        ("OBSERVATION", "INTERVIEW"),
        crit('የተፈጠረ የቴክኖሎጂ የግንኙነት ስርዓት አለ', 'Technology communication system exists'),
        crit('ጥቅም ላይ የሚውል መረጃ አለ', 'Evidence of effective use exists'),
    ),
    ind(
        "9.1", 1,
        'አመራሩ የአቅም ግንባታ መርሃ-ግብር አውጥቶ ተግባራዊ አድርጓል',
        'Leader developed and implemented capacity-building program',
        ("DOCUMENT_REVIEW"),
        crit('ለመምህራንና ለራሱ የአቅም ግንባታ መርሃ-ግብር አለ', 'Capacity-building program for teachers and self exists'),
        crit('የተሰጡ የአቅም ግንባታ ስልጠናዎች መረጃ አለ', 'Training records documented'),
    ),
    ind(
        "9.2", 1,
        'የአስተዳደር ሰራተኞችን ሙያዊ ማሻሻያ ተግባራት ተከናውኗል',
        'Professional development for admin staff implemented',
        ("DOCUMENT_REVIEW"),
        crit('ለአስተዳደር ሰራተኞች የአቅም ግንባታ መርሃ-ግብር አለ', 'Capacity program for admin staff exists'),
        crit('የተሰጡ የአቅም ግንባታ ስልጠናዎች መረጃ', 'Training records documented'),
    ),
    ind(
        "9.3", 1,
        'አመራሩ ከዩኒቨርሲቲ፣ ኮልጅ እና ኢንዱስትሪ ጋር ትስስር ፈጥሮ ድጋፍ አግኝቷል',
        'Leadership linked with universities, colleges and industry for support',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ት/ቤቱ የትስስር ስርዓት ዘርግቷል', 'School linkage system established'),
        crit('በተፈጠረ ትስስር የአቅም ግንባታ ድጋፍ አግኝቷል', 'Capacity support obtained through linkage'),
    ),
    ind(
        "10.1", 0.5,
        'የት/ቤቱ አመራር ኮሚቴዎችን በማደራጀት ተግባርና ኃላፊነት አውረደ',
        'Leadership organized committees and delegated responsibilities',
        ("DOCUMENT_REVIEW"),
        crit('ኮሚቴዎችን በመፍጠር የስራ ድልድል አድርጓል', 'Work delegation through committees established'),
    ),
    ind(
        "10.2", 1,
        'የተሰጠ ተግባርና ኃላፊነት አፈጻጸም ተደገፈ ተከታተለ እና ግብረ-መልስ ተሰጠ',
        'Committee performance supported, monitored and given feedback',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የመከታተያ ቼክ-ሊስት ተዘጋጅቷል', 'Monitoring checklist prepared'),
        crit('በተያዘ እቅድ መሰረት ድጋፍ ተሰጠ', 'Support provided per plan'),
        crit('ግብረ-መልስ ተሰጠ', 'Feedback provided'),
    ),
    ind(
        "10.3", 1,
        'የትምህርት ቤት መሻሻያ ኮሚቴ እቅድ አፈጻጸም ተከታተለ',
        'School improvement committee plan performance monitored',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የመሻሻያ ኮሚቴ የእቅድ አፈጻጸም ሪፖርቶች አሉ', 'Improvement committee performance reports exist'),
        crit('የተሰጡ ግብረ-መልሶችና የተሻሻሉ ጉዳዮች አሉ', 'Feedback and improved issues documented'),
    ),
    ind(
        "10.4", 0.5,
        'አመራሩ ማህበረሰብ የሚያሳትፍ የችግር መፍቻ ስርዓት ዘርግቷል',
        'Leader established inclusive problem-solving system',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ማህበረሰቡ በውሳኔ አሰጣጥ ሂደቶች ተሳትፏል', 'Community participated in decision-making'),
        crit('መምህራን በአመራር ሥራዎች ተሳትፈዋል', 'Teachers actively participate in leadership'),
        crit('መምህራንና ባለሙያዎች በግምገማ ተሳትፈዋል', 'Teachers and experts participated in assessment'),
        crit('ወላጆች በዓመት ቢያንስ ሶስት ጊዜ ተጠራተው ውይይት ተካሄደ', 'Parents convened at least three times yearly'),
        crit('ወላጆች የባለቤትነት ስሜት አላቸው', 'Parents have sense of ownership'),
    ),
    ind(
        "11.1", 1,
        'አመራሩ የውስጥ ሱፐርቪዥን ስርዓት በመዘርጋት ለመምህራን ሙያዊ ድጋፍ ሰጥቷል',
        'Leader provides professional support through internal supervision',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የተዘረጋ የውስጥ ሱፐርቪዥን ስርዓት አለ', 'Internal supervision system established'),
        crit('በተመጣጣኝ መጠን የሱፐርቪዥን ድጋፍ ተሰጠ', 'Proportional supervision support provided'),
    ),
    ind(
        "11.2", 1,
        'መምህራን ከ75% በላይ የክፍል ውስጥ ምልከታ እርስ በርስ ያደርጋሉ',
        'Teachers conduct peer classroom observation at least 75%',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('መምህራን በሴሚስተር ሶስት ጊዜ የዕርስ በርስ ሱፐርቪዥን ድጋፍ አድርገዋል', 'Teachers peer-supervised three times per semester'),
    ),
    ind(
        "11.3", 1,
        'መምህራን ተከታታይ ምዘና እና ግብረ-መልስ መስጠታቸውን ደገፈ',
        'Teachers supported continuous assessment and feedback',
        ("DOCUMENT_REVIEW"),
        crit('የተከታታይ ምዘና መከታተያ ቼክ-ሊስት ተዘጋጅቷል', 'Continuous assessment tracking checklist prepared'),
        crit('የተሰጠ ድጋፍና ግብረ-መልስ በመረጃ ተመዝግቧል', 'Support and feedback documented'),
    ),
    ind(
        "11.4", 1,
        'የመምህራንና ተማሪዎችን የአመራር ክህልት ለማሳደግ ስርዓት ተግባራዊ ሆኗል',
        'Leadership skill development system for teachers and students implemented',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('ተማሪዎች የአመራር ክህልት ለማሳደግ አሰራር ተግባራዊ ሆኗል', 'Student leadership development operational'),
        crit('በክouncelling፣ ክፍሎች፣ ኮሚቴዎች ተሳትፈው ክህልታቸው ይሳደጋል', 'Participation in clubs, classes, committees develops competence'),
    ),
    ind(
        "12.1", 1,
        'የት/ቤቱ አመራር ስኬታማ ግለሰቦችን በመጋበዝ ሙያዊ ተሞክሮዎችን እንዲያካፍሉ አድርጓል',
        'Leadership invited successful professionals to share experience',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ስኬታማ ግለሰቦችን በመጋበዝ ሙያዊ ተሞክሮዎችን እንዲያካፍሉ ተደርጓል', 'Successful professionals invited to share experience'),
    ),
    ind(
        "12.2", 1,
        'ለመምህራን ምቹ የስራ አካባቢ ተፈጥሯል',
        'Convenient work environment created for teachers',
        ("OBSERVATION"),
        crit('ለመደበኛ የሚያገለግሉ ስፍራዎች ተመቻችተዋል', 'Regular workspaces arranged'),
        crit('በግብዓት ተሟልተዋል', 'Resources are adequate'),
    ),
    ind(
        "12.3", 1,
        'የተሻለ አፈጻጸም ያላቸው መምህራን የሚበረታቱበት ግብርና ስርዓት ተግባራዊ ሆኗል',
        'Merit recognition system for high-performing teachers implemented',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የሚበረታቱበት የተዘረጋ ግብርና ሥርዓት አለ', 'Merit recognition system established'),
        crit('የተሻለ አፈጻጸም ያላቸው መምህራንን የማበረታታት ስራ ተሰርቷል', 'Recognition of high-performing teachers underway'),
    ),
    ind(
        "12.4", 1,
        'ሁሉም መምህራን በእኩልነት/ውሳኔ ሰጪነት የሚሳተፉበት ስርዓት ተግባራዊ ሆኗል',
        'System for equal/decision-making participation of all teachers implemented',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('መምህራን በእኩልነት የሚሳተፉበት ስርዓት ተዘርግቷል', 'Equal participation system established'),
        crit('በተዘረጋው ሥርዓት መሰረት ተግባራዊ ተደርጓል', 'System implemented in practice'),
    ),
    ind(
        "13.1", 0.5,
        'ሁሉም መምህራን በሰለጠኑበት የሙያ መስክ ተመድበዋል',
        'All teachers assigned in their trained subject field',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ሁሉም መምህራን በሰለጠኑበት የት/ት ዓይነት ተመድበዋል', 'All teachers assigned to trained subject'),
    ),
    ind(
        "13.2", 0.5,
        'ሁሉም የአስተዳደር ሰራተኞች በሰለጠኑበት የሙያ መስክ ተመድበዋል',
        'All admin staff assigned in their trained field',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ሁሉም አስተዳደር ሰራተኞች በሰለጠኑበት የት/ት ዓይነት ተመድበዋል', 'All admin staff assigned to trained field'),
    ),
    ind(
        "13.3", 1,
        'መምህራንና አስተዳደር ሰራተኞች በስራ ቦታ እና ሰዓት ተገኝተው ኃላፊነታቸውን ይወጣሉ',
        'Staff present at workplace and fulfill responsibilities',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የክትትል ስርዓት ተዘርግቷል', 'Monitoring system established'),
        crit('ኃላፊነት መወጣት የሚያሳይ ቅንጅታዊ አሰራር አለ', 'Organized work showing accountability exists'),
    ),
    ind(
        "13.4", 1,
        'የተጠያቂነት አሰራርና ስርዓት ተግባራዊ ሆኗል',
        'Accountability system implemented',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የተጠያቂነት አሰራርና ሥርዓት ተዘርግቷል', 'Accountability system established'),
        crit('የተወሰዱ እርምጃዎች አሉ', 'Corrective actions taken'),
    ),
    ind(
        "14.1", 1,
        'የተሰበሰበውን የፊይናንስ ሀብት ቅድሚያ ተግባራት ላይ ተዋል',
        'Mobilized financial resources allocated to priority activities',
        ("DOCUMENT_REVIEW"),
        crit('በትምህርት ቤቱ የፊይናንስ ድህረ-መዝገብ/ገቢ-ወጪ/ሚዛን አለ', 'School has income-expenditure-balance records'),
        crit('የተገኘ ሀብት ቅድሚያ ትኩረት ለሚገባው ተግባር ተዋለ', 'Resources allocated to priority activities'),
    ),
    ind(
        "14.2", 0.5,
        'አመራሩ ቁሳቁስና መሰረተ ልማት በአግባቡ አስተዳድሯል',
        'Leader appropriately manages assets and infrastructure',
        ("DOCUMENT_REVIEW"),
        crit('ቁሳቁስና መሰረተ ልማት የሚተዳደሩበት ስርዓት ተዘርግቷል', 'Asset management system established'),
        crit('በተዘረጋ ሥርዓት መሰረት ሀብት ተከናውኗል', 'Resources managed per established system'),
        crit('ለቁሳቁሶችና መሰረተ ልማቶች ወቅታዊ ጥገናና እድሳት ተደርጓል', 'Timely maintenance and renewal conducted'),
    ),
    ind(
        "14.3", 0.5,
        'የንብረትና ፊይናንስ ቁጥጥር ስርዓት ተግባራዊ ሆኗል',
        'Property and financial control system implemented',
        ("DOCUMENT_REVIEW"),
        crit('የንብረት ርክክብ መረጃዎች ተደራጅተው ተይዘዋል', 'Property balance records organized and maintained'),
        crit('የንብረት ቆጠራ/ኦዲት መረጃዎች ተደራጅተው ተይዘዋል', 'Asset audit records organized and maintained'),
        crit('ወቅታዊ የፊይናንስ ኦዲት ስራ ተከናውኗል', 'Current financial audit work conducted'),
        crit('በእቅድ መሰረት School report card ለማህበረሰቡ ተዘጋጅቷል', 'Community school report card prepared per plan'),
    ),
    ind(
        "15.1", 0.5,
        'ተማሪዎች የትምህርት ቁሳቁሶችን አሟሉተው ለትምህርት ዝግጁ ናቸው',
        'Students are ready for learning with complete materials',
        ("OBSERVATION", "INTERVIEW"),
        crit('ተማሪዎች ዩኒፎርም ለብሰው ይገኛሉ', 'Students attend in uniform per regulation'),
        crit('ተማሪዎች የመማሪያ ቁሳቁሶችን አሟሉተዋል', 'Students have complete learning materials'),
        crit('ተማሪዎች ቁሳቁሶችን በክፍል ውስጥ እየተጠቀሙበት', 'Students use materials in class'),
    ),
    ind(
        "15.2", 0.5,
        'ተማሪዎች በሰዓቱ በትምህርት ቤትና በክፍል ውስጥ ይገኛሉ',
        'Students attend school and class on time',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('ተማሪዎች በሰዓቱ በትምህርት ቤት ቅጥር ግቢ ይገኛሉ', 'Students present in compound on time'),
        crit('ተማሪዎች በሰዓቱ በክፍል ውስጥ ይገኛሉ', 'Students present in class on time'),
    ),
    ind(
        "15.3", 0.5,
        'ተማሪዎች በክፍል ውስጥና ውጭ ተግባራትን በንቃት ይሳተፋሉ',
        'Students actively participate in in-class and out-of-class activities',
        ("OBSERVATION", "INTERVIEW"),
        crit('ተማሪዎች የክፍልና የቤት ስራ በየጊዜው ይሰራሉ', 'Students do class and homework regularly'),
        crit('በጥንድ የሚያከናውኑት ስራዎች ይሰራሉ', 'Students complete pair work'),
        crit('የቡድን ስራዎች ይሰራሉ', 'Students complete group work'),
        crit('በቤተ-ሙከራ ሥራ ይሳተፋሉ', 'Students participate in lab work'),
    ),
    ind(
        "15.4", 1,
        'ተማሪዎች ጥያቄዎችን መጠየቅና መልስ መስጠት ይሳተፋሉ',
        'Students participate in asking and answering questions',
        ("OBSERVATION"),
        crit('ተማሪዎች አሳታፋዊ የመማር-ማስተማር ተግባር ተፈጥሯል', 'Participatory teaching-learning exists'),
        crit('ተማሪዎች በክፍል ውስጥና ውጭ በንቃት ይሳተፋሉ', 'Students actively participate in and out of class'),
    ),
    ind(
        "15.5", 0.5,
        'ተማሪዎች በተለያዩ ክlubs በንቁ ተሳትፈዋል',
        'Students actively participate in organized clubs',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('በመመሪያው መሰረት ክlubs ተደራጀ', 'Clubs organized per directive'),
        crit('ተማሪዎች በተጓዳኝ ክlub ንቁ ተሳትፈዋል', 'Students actively participate in relevant clubs'),
    ),
    ind(
        "15.6", 1,
        'ተማሪዎች አዲስ ነገር መፍጠርና ችግር መፍታት ይሞክራሉ',
        'Students attempt innovation and problem-solving',
        ("OBSERVATION", "INTERVIEW"),
        crit('ተማሪዎች በራስ-ተነሳሽነት የፈጠራ ስራዎችን ይሰራሉ', 'Students do creative work independently'),
        crit('የተማሪዎች የፈጠራ ስራዎች አሉ', 'Student creative works exist'),
        crit('የፈጠራ ስራዎች ችግር-ነፃ እንዲሆኑ ጥረት ተደርጓል', 'Efforts made to keep creative work problem-free'),
    ),
    ind(
        "15.7", 1,
        'ተማሪዎች የስራና ተግባር ትምህርትን በስራ ማሳያ ክፍል ይጠቀማሉ',
        'Students use work education in demonstration workshops',
        ("OBSERVATION"),
        crit('ትምህርት ቤቱ ስራ ማሳያዎች አዘጅቷል', 'School prepared demonstration workshops'),
        crit('ት/ቤቱ የማምረቻ ስፍራዎችን በመጠቀም ወደ ተግባር ገብቷል', 'School uses production spaces operationally'),
        crit('የእድ ጥበብና የእጅ ሥራዎች ተከናውኗል', 'Fine arts and handicrafts conducted'),
        crit('የእርሻ ስራዎች ተከናውኗል', 'Agriculture work conducted'),
        crit('የብረታ ብረትና የእንጨት ሥራዎች ተከናውኗል', 'Metal and wood work conducted'),
    ),
    ind(
        "16.1", 1,
        'መምህራን የተማሪዎችን አቀራ-ባል መሰረት በማድረግ የትምህርት እቅድ በአግባቡ አዘጅተዋል',
        'Teachers adequately plan lessons based on student context',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('መምህራን የትምህርት እቅድ አዘጅተዋል (አመታዊ፣ ወርሃዊ፣ ሳምንታዊ፣ ቀደሃዊ)', 'Teachers prepare lesson plans (annual, monthly, weekly, daily)'),
        crit('የትምህርት እቅድ አላማ፣ ይዘትና ተግባር ያካትታል', 'Plan includes objectives, content and roles'),
        crit('ቀደሃዊ እቅድ የምዘና ጥያቄዎችን በዝርዝር ያካትታል', 'Daily plan includes detailed assessment questions'),
    ),
    ind(
        "16.2", 1,
        'መምህራን የምዘና ዘዴ እና መርጃ መሳሪያዎችን በእቅድ ውስጥ ቀድተዋል',
        'Teachers plan assessment methods and teaching aids',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('በመምህር እቅድ የምዘና ዘዴ ተካቷል', 'Assessment method included in teacher plan'),
        crit('በመምህር እቅድ መርጃ መሳሪያዎች ተካተዋል', 'Teaching aids included in teacher plan'),
    ),
    ind(
        "17.1", 0.5,
        'መምህራን ተማሪዎችን በጥንድ፣ በቡድን እና በግል አሳታፋዊ ዘዴዎችን ይጠቀማሉ',
        'Teachers use pair, group and individual participatory methods',
        ("OBSERVATION"),
        crit('መምህራን አሳታፋዊ የማስተማር ዘዴዎችን ይቀይራሉ', 'Teachers vary participatory teaching methods'),
        crit('መምህራን አሳታፋዊ ዘዴዎችን ይተገብራሉ', 'Teachers implement participatory methods'),
    ),
    ind(
        "17.2", 0.5,
        'መምህራን ቴክኖሎጂ (ሬዲዮ፣ ቴልቪዥን፣ ኮምፒውተር) በመጠቀም ትምህርት ይሰጣሉ',
        'Teachers use technology in teaching',
        ("OBSERVATION"),
        crit('በትምህርት ቤቱ ICT አገልግሎት አለ', 'ICT service available in school'),
        crit('መምህራን ትምህርት በዘመናዊ ቴክኖሎጂ ይሰጣሉ', 'Teachers use modern technology in lessons'),
    ),
    ind(
        "17.3", 0.5,
        'መምህራን መርጃ መሳሪያዎችን በማዘጋጀት ጥቅም ላይ ይውላሉ',
        'Teachers prepare and use teaching aids',
        ("OBSERVATION"),
        crit('መምህራን መርጃ መሳሪያዎችን ያዘጋጃሉ', 'Teachers prepare teaching aids'),
        crit('መምህራን የትምህርት ቤቱን መርጃ መሳሪያዎችም ይጠቀማሉ', 'Teachers also use school-provided aids'),
    ),
    ind(
        "17.4", 0.5,
        'መምህራን ሳይንስ ኪት፣ ቤተ-ሙከራ እና Workshop በመጠቀም ትምህርት ይሰጣሉ',
        'Teachers use science kits, labs and workshops',
        ("OBSERVATION"),
        crit('መምህራን ሳይንስ ኪት/ቤተ-ሙከራ ይጠቀማሉ', 'Teachers use science kits/labs'),
        crit('መምህራን መስክ ምልከታ ይጠቀማሉ', 'Teachers use field observation'),
        crit('መምህራን Workshop ይጠቀማሉ', 'Teachers use workshops'),
    ),
    ind(
        "17.5", 0.5,
        'መምህራን ተማሪዎችን የፈጠራ/ሳይንስ ስራ እንዲሰሩ ያበረታታሉ',
        'Teachers encourage creative/science project work',
        ("OBSERVATION"),
        crit('መምህራን ተማሪዎችን በአካባቢ ቁሳቁስ የፈጠራ ስራ እንዲሰሩ ያበረታታሉ', 'Teachers encourage local-material creative work'),
        crit('በተማሪዎች የፈጠራ ስራዎች ተገቢነት ተመቻችቷል', 'Student creative work appropriately facilitated'),
    ),
    ind(
        "17.6", 0.5,
        'መምህሩ ባለሙያዎችን በመጋበዝ በመማር-ማስተማር ሂደት ይሳተፋል',
        'Teacher invites experts into teaching-learning',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('መምህራን ባለሙያ አካላትን ይidentifyዳሉ', 'Teachers identify relevant experts'),
        crit('መምህራን ባለሙያዎችን በትምህርት ይሳትፋሉ', 'Teachers involve experts in lessons'),
    ),
    ind(
        "17.7", 1,
        'መምህራን ችግሮችን ለመፍታት ተግባራዊ ጥናት/ምርምር ያካሂዳሉ',
        'Teachers conduct action research to solve problems',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('መምህራን ችግሮችን ለመፍታት ጥናት/ምርምር ያካሂዳሉ', 'Teachers conduct research to solve problems'),
        crit('ምቹ ሁኔታዎች ተፈጥረዋል', 'Conducive conditions created'),
        crit('መምህራን ችግሮችን ለመፍታት ጥናት/ምርምር አካሂደዋል', 'Teachers have conducted action research'),
        crit('የጥናቱ ግኝት በትምህርት ቤት ደረጃ ተግባር ላይ ገብቷል', 'Research findings applied at school level'),
        crit('መምህራን ጥረት አድርገዋል', 'Teachers made effort'),
        crit('ጥናቱ ተግባራዊ ሆኗል', 'Research is operational'),
    ),
    ind(
        "17.8", 1,
        'መምህራን ትምህርት ይዘትንና ቁልፍ ጽንሰ-ሀሳቦችን በተገቢ ቋንቋ ያቀርባሉ',
        'Teachers present content and key concepts in appropriate language',
        ("OBSERVATION"),
        crit('መምህራን ይዘትና ቁልፍ ሀሳቦችን በተገቢ ቋንቋና አቀራ-ባል ያቀርባሉ', 'Teachers present content in appropriate language and approach'),
    ),
    ind(
        "18.1", 1,
        'መምህራን ምዘናን በስርዓተ-ትምህርት እና Table of Specifications መሰረት ያዘጋጃሉ',
        'Teachers prepare assessment based on curriculum and table of specifications',
        ("DOCUMENT_REVIEW", "OBSERVATION"),
        crit('መምህራን በTable of Specifications ግንዛቤ አላቸው', 'Teachers understand table of specifications'),
        crit('መምህራን ምዘና ስርዓተ-ትምህርትን መሰረት ያደረገ', 'Assessment based on curriculum'),
        crit('መምህራን ምዘና በTable of Specifications መሰረት', 'Assessment based on table of specifications'),
        crit('በትምህርት ክፍሎች የሚዘጋጁ ምዘናዎች ተገምግመዋል', 'Class assessments reviewed'),
        crit('ምዘናዎች ተመሳሳይነት አላቸው', 'Assessments are consistent'),
    ),
    ind(
        "18.2", 1,
        'መምህራን ተማሪዎችን በMLC መሰረት ተከታታይ ምዘና ይሰጣሉ',
        'Teachers give continuous assessment based on MLC',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('መምህራን ተከታታይ ምዘና ስርዓት ይረዳሉ', 'Teachers understand continuous assessment'),
        crit('ተከታታይ ምዘና በMLC መሰረት', 'Continuous assessment based on MLC'),
        crit('ክፍሎች ተከታታይ ምዘናን ይረዳሉ', 'Classes understand continuous assessment'),
        crit('ተከታታይ ምዘና ተግባር ላይ ነው', 'Continuous assessment operational'),
    ),
    ind(
        "18.3", 0.5,
        'መምህራን ተከታታይ ምዘናን በመጠቀም ግብረ-መልስ ይሰጣሉ',
        'Teachers use continuous assessment to give feedback',
        ("DOCUMENT_REVIEW"),
        crit('መምህራን ተከታታይ ምዘና ውጤትን ይመዘግባሉ', 'Teachers record continuous assessment results'),
        crit('መምህራን በወቅቱ ግብረ-መልስ ይሰጣሉ', 'Teachers give timely feedback'),
    ),
    ind(
        "18.4", 1,
        'መምህራን ዝቅተኛ ውጤት ያላቸውን ተማሪዎች ተጨማሪ ድጋፍ ይሰጣሉ',
        'Teachers give additional support to low achievers',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ዝቅተኛ ውጤት ያላቸው ተማሪዎች ዝርዝር ተመዝግቧል', 'Low achievers list maintained'),
        crit('ዝቅተኛ achievers ተጨማሪ ድጋፍ ተሰጥቷል', 'Additional support provided to low achievers'),
        crit('መምህራን የውጤት ትንተና ሰርተዋል', 'Teachers conducted results analysis'),
    ),
    ind(
        "18.5", 0.5,
        'መምህራን በሴሚስተር አጋማሽ ውጤትን ለወላጆች በማሳወቅ ግብረ-መልስ ይቀበላሉ',
        'Teachers share semester results with parents and receive feedback',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('መምህራን የውጤት ማሳወቂያ/ግብረ-መልስ ስርዓት ዘርገተዋል', 'Results reporting/feedback system established'),
        crit('መምህራን ውጤትን ለወላጆች በሴሚስተር አጋማሽ አሳውቀዋል', 'Results shared with parents mid-semester'),
        crit('መምህራን ከወላጆች ግብረ-መልስ ተቀብለዋል', 'Teachers received parent feedback'),
    ),
    ind(
        "19.1", 2,
        'መምህራን የስርዓተ-ትምህርት/ሰነዶችን በግልና በቡድን ገምግመው ግብረ-መልስ ይሰጣሉ እና ከት/ጽ/ቤት ግምገማ አስተያየት ይቀበላሉ',
        'Teachers review curriculum materials collaboratively and receive textbook office evaluation feedback',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('መምህራን የስርዓተ-ትምህርት ሰነዶችን ለመገምገም ስርዓት ዘርገተዋል', 'System to review curriculum documents established'),
        crit('መምህራን መርሃ-ትምህርቶችን በግል ገምግመዋል', 'Teachers individually reviewed lesson materials'),
        crit('መምህራን መርሃ-ትምህርቶችን በጋራ ገምግመዋል', 'Teachers collaboratively reviewed lesson materials'),
        crit('መምህራን የስርዓተ-ትምህርት ግምገማ ግብረ-መልስ በደረጃ ይቀበላሉ', 'Teachers receive staged curriculum review feedback'),
        crit('ትምህርት ቤቱ የስርዓተ-ትምህርት ግምገማ ሪፖርት ከት/ጽ/ቤት አስተያየት ይቀበላል', 'School receives textbook office comments on curriculum review report'),
        crit('ትምህርት ቤቱ ከተመለከተው አካሊት የስርዓተ-ትምህርት ግምገማ አስተያየት ይቀበላል', 'School receives curriculum review feedback from relevant body'),
    ),
    ind(
        "19.3", 1,
        'መምህራን በጋራ Lesson study/planning ተግባራትን አከናውኗል',
        'Teachers conducted collaborative lesson study/planning',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('በየትምህርት ክፍል የጋራ ግንዛቤ ተፈጥሯል', 'Shared understanding per subject created'),
        crit('በጋራ ግንዛቤ መሰረት ተግባራዊ ተደርጓል', 'Implemented based on shared understanding'),
    ),
    ind(
        "20.1", 1.5,
        'አዲስ ጀማሪ መምህራን Induction ተግባራዊ አድርገዋል ነባር መምህራን CPD ተግብረዋል',
        'New teachers completed induction; existing teachers completed CPD',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('አዲስ ጀማሪ መምህራን Induction Course አጠናቀቁ', 'New teachers completed induction course'),
        crit('ነባር መምህራን 60-ሰዓት CPD አጠናቀቁ', 'Existing teachers completed 60-hour CPD'),
    ),
    ind(
        "20.2", 1.5,
        'የት/ቤት አመራሮች CPD ተግባራዊ አድርገዋል',
        'School leaders implemented CPD',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ር/መምህራን 60-ሰዓት CPD አጠናቀቁ', 'Principal completed 60-hour CPD'),
        crit('ሱፐርቫይዘር CPD ለትምህርት ቤቱ ድጋፍ አድርጓል', 'Supervisor CPD supports the school'),
    ),
    ind(
        "21.1", 2,
        'ትምህርት ቤቱ ከተማሪ ወላጆች ጋር ቋሚ የግንኙነት ጊዜ ፈጥሮ ተግባራዊ አድርጓል',
        'School established and implements regular parent communication',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ትምህርት ቤቱ ከወላጆች ጋር የሚገናኝበት ስርዓት ዘርጎቷል', 'Parent communication system established'),
        crit('ወላጆች የተዘረጋውን ስርዓት ይረዳሉ', 'Parents understand the system'),
        crit('የተዘረጋው ስርዓት ተግባራዊ ሆኗል', 'System implemented'),
    ),
    ind(
        "21.2", 2,
        'ወላጆች በኮሚቴዎች፣ አደረጃጀቶች እና መድረኮች በንቃት ይሳተፋሉ',
        'Parents actively participate in committees and forums',
        ("INTERVIEW", "DOCUMENT_REVIEW"),
        crit('ትምህርት ቤቱ ወላጆችን በኮሚቴዎች/Aደረጃጀቶች ይሳተፋል', 'Parents participate in committees/structures'),
        crit('ወላጆች ስርዓቱን ይረዳሉ', 'Parents understand participation system'),
        crit('ወላጆች ተግባራዊ ተሳትፈዋል', 'Parents actively participate'),
    ),
    ind(
        "22.1", 3,
        'ወላጆች በገንዘብ፣ በአይነት፣ በእውቀትና በጉልበት ለትምህርት ቤቱ ድጋፍ አድርገዋል',
        'Parents contribute cash, in-kind, knowledge and labour',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ከእቅድ አንፃር የጉልበት ድጋፍ', 'Labour support per plan'),
        crit('ከእቅድ አንፃር የገንዘብ ድጋፍ', 'Cash support per plan'),
        crit('ከእቅድ አንፃር የአይነት ድጋፍ', 'In-kind support per plan'),
        crit('ከእቅድ አንፃር በእውቀት ድጋፍ', 'Knowledge support per plan'),
    ),
    ind(
        "22.2", 3,
        'ከማህበረሰብ፣ ቀደም ተማሪዎች እና ተቋማት ለትምህርት ቤቱ ድጋፍ ተሰጥቷል',
        'Community, alumni and institutions contributed to the school',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ከእቅድ አንፃር የጉልበት ድጋፍ', 'Labour support per plan'),
        crit('ከእቅድ አንፃር የገንዘብ ድጋፍ', 'Cash support per plan'),
        crit('ከእቅድ አንፃር የአይነት ድጋፍ', 'In-kind support per plan'),
        crit('ከእቅድ አንፃር በእውቀት ድጋፍ', 'Knowledge support per plan'),
    ),
    ind(
        "23.1", 1,
        'ትምህርት ቤቱ ለማህበረሰብ አገልግሎት የሚያስችል ስርዓት ዘርጎ ተግባራዊ አድርጓል',
        'School established community service system',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የማህበረሰብ አገልግሎት ሥርዓት ተዘርግቷል', 'Community service system established'),
        crit('የተዘረጋው አሰራር ተሰማይቷል', 'Operational approach communicated'),
        crit('የተዘረጋው አሰራር ተግባራዊ ሆኗል', 'Approach implemented'),
    ),
    ind(
        "23.2", 1,
        'ትምህርት ቤቱ ለማህበረሰብ የመማማሪያ/መመከሪያ/ልምድ-መแลก ማዕከል ሆኗል',
        'School serves as community learning/counselling/experience centre',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ማህበረሰብ ሀብቶችን እንዲጠቀም የተዘጋ ስርዓት ተግባራዊ ሆኗል', 'System for community use of resources operational'),
        crit('ማህበረሰብ ሀብቶችን እንዲጠቀም ተደርጓል', 'Community enabled to use school resources'),
    ),
    ind(
        "24.1", 0.5,
        'ወላጆች ለልጆቻቸው ውጤት መሻሻያ ድጋፍ አድርገዋል',
        "Parents support children's learning improvement",
        ("INTERVIEW", "DOCUMENT_REVIEW"),
        crit('ለተማሪዎች የሚያስፈልጉ ግብዓቶች ተሟልተዋል', 'Required inputs for students provided'),
        crit('የቤት/ክፍል ስራና ፕሮጀክቶች ተከታተለ', 'Home/class work and projects monitored'),
    ),
    ind(
        "24.2", 1,
        'ወላጆች ልጆቻቸው በትምህርት ገበታ ላይ እንዲገኙ ተከታተለ',
        "Parents monitor children's attendance at learning",
        ("INTERVIEW"),
        crit('ወላጆች ልጆቻቸው በትምህርት ገበታ ይገኛሉ', 'Parents ensure children attend learning sessions'),
    ),
    ind(
        "24.3", 0.5,
        'ወላጆች ለልጆቻቸው ባህሪ መሻሻያ የድርሻቸውን ይወጣሉ',
        'Parents fulfill role in behaviour improvement',
        ("INTERVIEW"),
        crit('ወላጆች የባህሪ ድጋፍ ጥያቄዎችን አፈጽመዋል', 'Parents respond to behaviour support requests'),
        crit('ወ.ተ.መ.ህ ለወላጆች ግንዛብ ፈጥሯል', 'PTA created parent awareness on behaviour'),
    ),
    ind(
        "24.4", 1,
        'የተማሪ ወላጅ-መምህር ግንኙነት ጠንካራ ሆኗል',
        'Parent-teacher relationship strengthened',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('ወ.ተ.መ.ህ አመታዊ እቅድ አዘጅቷል', 'PTA prepared annual plan'),
        crit('ወ.ተ.መ.ህ በእቅድ መሰረት ግንኙነት አካሂዷል', 'PTA conducted planned engagement'),
        crit('ወ.ተ.መ.ህ እቅድን ተግባራዊ አድርጓል', 'PTA implemented plan'),
        crit('የግንኙነት መዝገቦች አሉ', 'Engagement records exist'),
    ),
    ind(
        "25.1", 0.5,
        'ትምህርት ቤቱ መጠነ-ማቋረጥ በዕቅድ ቀንሷል',
        'School reduced dropout rate per plan',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የታቀደው መጠነ-ማቋረጥ ግብ ተሳክቷል', 'Planned dropout reduction target achieved'),
    ),
    ind(
        "25.2", 1.5,
        'ትምህርት ቤቱ መጠነ-መደገም በዕቅድ ቀንሷል',
        'School reduced repetition rate per plan',
        ("DOCUMENT_REVIEW", "INTERVIEW"),
        crit('የታቀደው መጠነ-መደገም ግብ ተሳክቷል', 'Planned repetition reduction target achieved'),
    ),
    ind(
        "25.3", 1,
        'ትምህርት ቤቱ መጠነ-ማርፍድ በዕቅድ ቀንሷል',
        'School reduced wastage rate per plan',
        ("DOCUMENT_REVIEW"),
        crit('የታቀደው መጠነ-ማርፍድ ግብ ተሳክቷል', 'Planned wastage reduction target achieved'),
    ),
    ind(
        "25.4", 1.5,
        'የትምህርት ቤቱ የማሳለፍ ምጣኔ ጨምሯል/ተሻሽሏል',
        'School promotion rate increased/improved',
        ("DOCUMENT_REVIEW"),
        crit('ከክፍል-ክፍል ዝውውር በእቅድ ተሻሽሏል', 'Grade-to-grade promotion improved per plan'),
        crit('በክሊኒክ ፈተና የማሳለፍ ምጣኔ ተሻሽሏል', 'Clinical exam promotion rate improved'),
        crit('በብሄራዊ ፈተና የማሳለፍ ምጣኔ ተሻሽሏል', 'National exam promotion rate improved'),
    ),
    ind(
        "26.1", 1.5,
        'ሁሉም ተማሪዎች በክፍል ፈተና በእያንዳንዱ የትምህርት ዓይነት 50% እና በላይ',
        'All students score 50%+ in each subject on class exams',
        ("DOCUMENT_REVIEW"),
        crit('ሁሉም ተማሪዎች በእያንዳንዱ የትምህርት ዓይነት 50%+ ውጤት', 'All students score 50%+ per subject'),
    ),
    ind(
        "26.2", 1.5,
        'ሁሉም ተማሪዎች በ6ኛ ክፍል ክሊኒክ ፈተና 50%+',
        'All students score 50%+ on grade 6 clinical exam',
        ("DOCUMENT_REVIEW"),
        crit('ሁሉም ተማሪዎች በ6ኛ ክፍል ክሊኒክ 50%+', 'All students score 50%+ on grade 6 clinical exam'),
    ),
    ind(
        "26.3", 1.5,
        'ሁሉም ተማሪዎች በ8ኛ ክፍል ፈተና 50%+',
        'All students score 50%+ on grade 8 exam',
        ("DOCUMENT_REVIEW"),
        crit('ሁሉም ተማሪዎች በ8ኛ ክፍል 50%+', 'All students score 50%+ on grade 8 exam'),
    ),
    ind(
        "26.4", 1,
        'በትምህርት ቤቱ ተከታታይ የተሻሻለ የተማሪ ውጤት ምዝገባ ልምድ ተዲብሯል',
        'Culture of recording improving student results established',
        ("DOCUMENT_REVIEW"),
        crit('ባለፈት 3 አመት ክሊኒክ ፈተና ውጤት ተሻሽሏል', 'Clinical exam results improved over 3 years'),
        crit('ባለፈት 3 አመት ሀገራዊ ፈተና ውጤት ተሻሽሏል', 'National exam results improved over 3 years'),
    ),
    ind(
        "26.5", 1,
        'ለሴት ተማሪዎች በልዩ ድጋፍ 50%+ ውጤት',
        'Female students score 50%+ with special support',
        ("DOCUMENT_REVIEW"),
        crit('ሴት ተማሪዎች በልዩ ድጋፍ 50%+ ውጤት', 'Female students score 50%+ with special support'),
    ),
    ind(
        "26.6", 1,
        'ልዩ የትምህርት ፍላጎት ተማሪዎች በልዩ ድጋፍ 50%+',
        'Special needs students score 50%+ with special support',
        ("DOCUMENT_REVIEW"),
        crit('ልዩ ፍላጎት ተማሪዎች በልዩ ድጋፍ 50%+', 'Special needs students score 50%+ with special support'),
    ),
    ind(
        "26.7", 1,
        'ሁሉም ተማሪዎች በተግባር ፈተና በሰለጠኑበት መስክ ብቁ ናቸው',
        'All students competent in practical exam for trained field',
        ("DOCUMENT_REVIEW"),
        crit('ሁሉም ተማሪዎች በተግባር ፈተና ብቁ', 'All students competent on practical exam'),
    ),
    ind(
        "27.1", 1,
        'ተማሪዎች የሚፈጸም ኩረጃ ፀያፍ መሆኑን ተገንዝበው በተግባር ያሳያሉ',
        'Students reject cheating culture and demonstrate integrity',
        ("OBSERVATION", "INTERVIEW"),
        crit('የጸረ-ኩረጃ ስርዓት ተባይነት አግኝቷል', 'Anti-cheating system accepted'),
        crit('የኮራጅ ተማሪዎች ቁጥር ቀንሷል', 'Courageous/integrity student numbers increased'),
    ),
    ind(
        "27.2", 1,
        'በተማሪዎች መካከል በጎ ፍቃደ-መረዳዳት ባህል ተዲብሯል',
        'Culture of peer support established',
        ("OBSERVATION", "INTERVIEW"),
        crit('የመተላለፊያ ቁሳቁሶች ማሰባሰብና ተዛማጅ ስርዓት', 'Peer material sharing system established'),
        crit('ተማሪዎች እርስ በርስ በትምህርት ይረዳሉ', 'Students support each other in learning'),
    ),
    ind(
        "27.3", 1,
        'የተማሪዎች የመከባበር ባህል ተዲብሯል',
        'Student respect culture developed',
        ("OBSERVATION", "INTERVIEW"),
        crit('ተማሪዎች እርስ በርስ የመከባበር ባህል', 'Students respect each other'),
        crit('ተማሪዎች መምህራንንና አመራሩን ይ respectላሉ', 'Students respect teachers and leaders'),
        crit('ተማሪዎች ግዳታቸውን ተወጥተው ይታገላሉ', 'Students fulfill duties patiently'),
        crit('ተማሪዎች የመተማመን ልምድ ጎልብቷል', 'Trust culture improved'),
        crit('ተማሪዎች ት/ቤት ማህበረሰብን ይ respectላሉ', 'Students respect school community'),
    ),
    ind(
        "27.4", 1,
        'ተማሪዎች ሃሳባቸውን በራስ-መተማመን ይግለጻሉ',
        'Students express ideas with self-confidence',
        ("OBSERVATION", "INTERVIEW"),
        crit('ተማሪዎች በStudent council/parliament ሃሳባቸውን ያቀርባሉ', 'Students express ideas through student council'),
        crit('ተማሪዎች በራስ-መተማመን ልምድ ጎልብተዋል', 'Students developed self-confidence'),
    ),
    ind(
        "28.1", 1,
        'በትምህርት ቤቱ የተዘጋጀው መተዳደሪያ መንግስት አጋዥነት ሰላማዊ አካባቢ ፈጥሯል',
        'Prepared regulatory framework supports peaceful school environment',
        ("OBSERVATION", "INTERVIEW"),
        crit('ተማሪዎች የትምህርት ቤቱን መተዳደሪያ መንግስት ይ respectላሉ', 'Students respect school regulations'),
        crit('መምህራን የትምህርት ቤቱን መተዳደሪያ መንግስት ይ respectላሉ', 'Teachers respect school regulations'),
        crit('ድጋፍ ሰጪ ሰራተኞች መተዳደሪያ መንግስት ይ respectላሉ', 'Support staff respect regulations'),
    ),
    ind(
        "28.2", 1,
        'በትምህርት ማህበረሰብ የመረዳዳት/መከባበር ባህል ተዲብሯል',
        'Mutual support/respect culture in school community developed',
        ("OBSERVATION", "DOCUMENT_REVIEW"),
        crit('መረዳዳትን ለማስፈን ስልቶች ተተግብረዋል', 'Strategies to promote mutual support implemented'),
        crit('በማህበረሰብ መካከል የመከባበር ባህል ተዲብሯል', 'Respect culture among community developed'),
    ),
    ind(
        "28.3", 1,
        'ተማሪዎች ትምህርት ቤታቸውንና አካባቢያቸውን ይንከባከባሉ',
        'Students care for school and environment',
        ("OBSERVATION"),
        crit('ተማሪዎች ትምህርት ቤታቸውን ይንከባከባሉ', 'Students care for their school'),
        crit('ተማሪዎች የትምህርት ቤታቸውን አካባቢ ይንከባከባሉ', 'Students care for school environment'),
        crit('ተማሪዎች አካባቢን መጠበቅ ይሰራሉ', 'Students work to protect environment'),
    ),
]

assert len(ALL_INDICATOR_SPECS) == 100
assert sum(len(s["criteria"]) for s in ALL_INDICATOR_SPECS) == 304

